// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'secondary': string;
  'wide': string;
}
export const cssExports: CssExports;
export default cssExports;
