// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'abilities': string;
  'count': string;
  'data': string;
  'image': string;
  'item': string;
  'order': string;
  'pokemonModal': string;
  'root': string;
  'stats': string;
}
export const cssExports: CssExports;
export default cssExports;
