// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'lds-hourglass': string;
  'root': string;
  'spinner': string;
}
export const cssExports: CssExports;
export default cssExports;
