// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'pokedex': string;
  'pokedexWrapper': string;
  'search': string;
}
export const cssExports: CssExports;
export default cssExports;
